/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['hooks/generic-hook.js']) {
  _$jscoverage['hooks/generic-hook.js'] = [];
  _$jscoverage['hooks/generic-hook.js'][1] = 0;
  _$jscoverage['hooks/generic-hook.js'][2] = 0;
  _$jscoverage['hooks/generic-hook.js'][3] = 0;
  _$jscoverage['hooks/generic-hook.js'][4] = 0;
  _$jscoverage['hooks/generic-hook.js'][6] = 0;
  _$jscoverage['hooks/generic-hook.js'][7] = 0;
  _$jscoverage['hooks/generic-hook.js'][8] = 0;
  _$jscoverage['hooks/generic-hook.js'][10] = 0;
  _$jscoverage['hooks/generic-hook.js'][11] = 0;
  _$jscoverage['hooks/generic-hook.js'][13] = 0;
  _$jscoverage['hooks/generic-hook.js'][14] = 0;
  _$jscoverage['hooks/generic-hook.js'][15] = 0;
  _$jscoverage['hooks/generic-hook.js'][16] = 0;
  _$jscoverage['hooks/generic-hook.js'][17] = 0;
  _$jscoverage['hooks/generic-hook.js'][21] = 0;
  _$jscoverage['hooks/generic-hook.js'][22] = 0;
  _$jscoverage['hooks/generic-hook.js'][24] = 0;
}
_$jscoverage['hooks/generic-hook.js'][1]++;
var GenericHook = (function () {
});
_$jscoverage['hooks/generic-hook.js'][2]++;
GenericHook.prototype.ctor = (function () {
  _$jscoverage['hooks/generic-hook.js'][3]++;
  this.client_map = {};
  _$jscoverage['hooks/generic-hook.js'][4]++;
  this.listen();
});
_$jscoverage['hooks/generic-hook.js'][6]++;
GenericHook.prototype.add_client = (function (client) {
  _$jscoverage['hooks/generic-hook.js'][7]++;
  this.client_map[client.id] = client;
  _$jscoverage['hooks/generic-hook.js'][8]++;
  this.send_to_client(client);
});
_$jscoverage['hooks/generic-hook.js'][10]++;
GenericHook.prototype.remove_client = (function (client) {
  _$jscoverage['hooks/generic-hook.js'][11]++;
  delete this.client_map[client.id];
});
_$jscoverage['hooks/generic-hook.js'][13]++;
GenericHook.prototype.send = (function (data) {
  _$jscoverage['hooks/generic-hook.js'][14]++;
  var k;
  _$jscoverage['hooks/generic-hook.js'][15]++;
  for (k in this.client_map) {
    _$jscoverage['hooks/generic-hook.js'][16]++;
    if (this.client_map.hasOwnProperty(k)) {
      _$jscoverage['hooks/generic-hook.js'][17]++;
      this.send_to_client(this.client_map[k], data);
    }
}
});
_$jscoverage['hooks/generic-hook.js'][21]++;
GenericHook.prototype.listen = (function () {
});
_$jscoverage['hooks/generic-hook.js'][22]++;
GenericHook.prototype.send_to_client = (function (client) {
});
_$jscoverage['hooks/generic-hook.js'][24]++;
module.exports = GenericHook;
_$jscoverage['hooks/generic-hook.js'].source = ["var GenericHook = function(){};","GenericHook.prototype.ctor = function(){","\tthis.client_map = {};","\tthis.listen();","};","GenericHook.prototype.add_client = function(client){","\tthis.client_map[client.id] = client;","\tthis.send_to_client(client);","};","GenericHook.prototype.remove_client = function(client){","\tdelete this.client_map[client.id];","};","GenericHook.prototype.send = function(data){","\tvar k;","\tfor(k in this.client_map){","\t\tif(this.client_map.hasOwnProperty(k)){","\t\t\tthis.send_to_client(this.client_map[k], data);","\t\t}","\t}","}","GenericHook.prototype.listen = function(){};","GenericHook.prototype.send_to_client = function(client){};","","module.exports = GenericHook;"];
